name: fsy_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.1
  dart_jsonwebtoken: ^3.4.1
  flutter_dotenv: ^6.0.1
  mobile_scanner: ^7.2.0
  blue_thermal_printer: ^1.1.7          # replaced flutter_thermal_printer
  provider: ^6.1.2
  uuid: ^4.4.0
  intl: ^0.20.2
  connectivity_plus: ^7.1.1
  logging: ^1.2.0
  audioplayers: ^6.0.0  
  path_provider: ^2.1.2
  wakelock_plus: ^1.2.8
  flutter_tts: ^4.0.2
  fl_chart: ^1.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1   

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/fsy_logo.png
    - assets/transparent_background_fsy_logo.png
    - assets/transparent_qr_code_logo_success.png
    - assets/transparent_qr_code_logo_error.png
    - assets/error_sound.mp3
    - assets/success_sound.mp3
    - assets/warning_sound.mp3

flutter_launcher_icons:
  android: true
  image_path: "assets/transparent_background_fsy_logo.png"
